package com.learning.testingcasemgmt2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Empleado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Nombre")
	private java.lang.String nombre;

	public Empleado() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public Empleado(java.lang.String nombre) {
		this.nombre = nombre;
	}

}